### ISSUE TITLE
Issue with main.py

### ISSUE THREAD

**Issue by thisadamis** [stettberger/ledger-funds#1]
First of all THANK you so much for creating this. It is helping a ton. However when i run the main.py script I get the following error. I am runnning python main.py. I am also on Ubuntu 18.04. Any ideas?

Traceback (most recent call last):
  File "main.py", line 4, in <module>
    import ledger
ImportError: No module named ledger

**Comment by stettberger** [comment]
You should install python3-ledger in order to get the Python bindings.

Am 11. Januar 2019 22:53:46 MEZ schrieb thisconstantreader <notifications@github.com>:
>First of all THANK you so much for creating this. It is helping a ton.
>However when i run the main.py script I get the following error. I am
>runnning python main.py. I am also on Ubuntu 18.04. Any ideas?
>
>Traceback (most recent call last):
>  File "main.py", line 4, in <module>
>    import ledger
>ImportError: No module named ledger
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/stettberger/ledger-funds/issues/1

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by thisadamis** [comment]
Is that this command? python3 -m pip install ledger

**Comment by thisadamis** [comment]
I'm sorry I am new to ledger and I don't know much about python...

**Comment by stettberger** [comment]
Ah, sorry. main.py is a Python2 script as Ubuntu only provides a python2 package for ledger (`python-ledger`). Therefore, you should be able to use apt-get or `python -m pip install ledger`.

**Comment by stettberger** [comment]
As this is not really related to the purpose of this github, but a general Python question. I will close this bug.
